// Generated by gencpp from file jackal_robot_localization/SetPose.msg
// DO NOT EDIT!


#ifndef JACKAL_ROBOT_LOCALIZATION_MESSAGE_SETPOSE_H
#define JACKAL_ROBOT_LOCALIZATION_MESSAGE_SETPOSE_H

#include <ros/service_traits.h>


#include <jackal_robot_localization/SetPoseRequest.h>
#include <jackal_robot_localization/SetPoseResponse.h>


namespace jackal_robot_localization
{

struct SetPose
{

typedef SetPoseRequest Request;
typedef SetPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPose
} // namespace jackal_robot_localization


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jackal_robot_localization::SetPose > {
  static const char* value()
  {
    return "4f3e0bbe7a24e1f929488cd1970222d3";
  }

  static const char* value(const ::jackal_robot_localization::SetPose&) { return value(); }
};

template<>
struct DataType< ::jackal_robot_localization::SetPose > {
  static const char* value()
  {
    return "jackal_robot_localization/SetPose";
  }

  static const char* value(const ::jackal_robot_localization::SetPose&) { return value(); }
};


// service_traits::MD5Sum< ::jackal_robot_localization::SetPoseRequest> should match
// service_traits::MD5Sum< ::jackal_robot_localization::SetPose >
template<>
struct MD5Sum< ::jackal_robot_localization::SetPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jackal_robot_localization::SetPose >::value();
  }
  static const char* value(const ::jackal_robot_localization::SetPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jackal_robot_localization::SetPoseRequest> should match
// service_traits::DataType< ::jackal_robot_localization::SetPose >
template<>
struct DataType< ::jackal_robot_localization::SetPoseRequest>
{
  static const char* value()
  {
    return DataType< ::jackal_robot_localization::SetPose >::value();
  }
  static const char* value(const ::jackal_robot_localization::SetPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jackal_robot_localization::SetPoseResponse> should match
// service_traits::MD5Sum< ::jackal_robot_localization::SetPose >
template<>
struct MD5Sum< ::jackal_robot_localization::SetPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jackal_robot_localization::SetPose >::value();
  }
  static const char* value(const ::jackal_robot_localization::SetPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jackal_robot_localization::SetPoseResponse> should match
// service_traits::DataType< ::jackal_robot_localization::SetPose >
template<>
struct DataType< ::jackal_robot_localization::SetPoseResponse>
{
  static const char* value()
  {
    return DataType< ::jackal_robot_localization::SetPose >::value();
  }
  static const char* value(const ::jackal_robot_localization::SetPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JACKAL_ROBOT_LOCALIZATION_MESSAGE_SETPOSE_H
