// Generated by gencpp from file jackal_robot_localization/ToggleFilterProcessingRequest.msg
// DO NOT EDIT!


#ifndef JACKAL_ROBOT_LOCALIZATION_MESSAGE_TOGGLEFILTERPROCESSINGREQUEST_H
#define JACKAL_ROBOT_LOCALIZATION_MESSAGE_TOGGLEFILTERPROCESSINGREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jackal_robot_localization
{
template <class ContainerAllocator>
struct ToggleFilterProcessingRequest_
{
  typedef ToggleFilterProcessingRequest_<ContainerAllocator> Type;

  ToggleFilterProcessingRequest_()
    : on(false)  {
    }
  ToggleFilterProcessingRequest_(const ContainerAllocator& _alloc)
    : on(false)  {
  (void)_alloc;
    }



   typedef uint8_t _on_type;
  _on_type on;





  typedef boost::shared_ptr< ::jackal_robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jackal_robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ToggleFilterProcessingRequest_

typedef ::jackal_robot_localization::ToggleFilterProcessingRequest_<std::allocator<void> > ToggleFilterProcessingRequest;

typedef boost::shared_ptr< ::jackal_robot_localization::ToggleFilterProcessingRequest > ToggleFilterProcessingRequestPtr;
typedef boost::shared_ptr< ::jackal_robot_localization::ToggleFilterProcessingRequest const> ToggleFilterProcessingRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jackal_robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jackal_robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jackal_robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator1> & lhs, const ::jackal_robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator2> & rhs)
{
  return lhs.on == rhs.on;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jackal_robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator1> & lhs, const ::jackal_robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jackal_robot_localization

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::jackal_robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jackal_robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jackal_robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jackal_robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jackal_robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jackal_robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jackal_robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "74983d2ffe4877de8ae30b7a94625c41";
  }

  static const char* value(const ::jackal_robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x74983d2ffe4877deULL;
  static const uint64_t static_value2 = 0x8ae30b7a94625c41ULL;
};

template<class ContainerAllocator>
struct DataType< ::jackal_robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jackal_robot_localization/ToggleFilterProcessingRequest";
  }

  static const char* value(const ::jackal_robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jackal_robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool on\n"
;
  }

  static const char* value(const ::jackal_robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jackal_robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.on);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ToggleFilterProcessingRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jackal_robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jackal_robot_localization::ToggleFilterProcessingRequest_<ContainerAllocator>& v)
  {
    s << indent << "on: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.on);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JACKAL_ROBOT_LOCALIZATION_MESSAGE_TOGGLEFILTERPROCESSINGREQUEST_H
