#!/usr/bin/env python

#!/usr/bin/env python
import rospy
from sensor_msgs.msg import NavSatFix

class Waypoint(object):
  def __init__(self, id, latitude, longitude):
    self.id = id
    self.latitude = latitude
    self.longitude = longitude

class SendWaypoints(object):

  def __init__(self):
    rospy.init_node('waypoint_list', anonymous=True)
    # Publishers
    # Publishes waypoint
    self.goal_pub = rospy.Publisher('/waypoint_coordinator/goal_request', NavSatFix, queue_size=5)
    rospy.sleep(0.5)

  def execute(self, waypoint):
    msg = NavSatFix()
    msg.latitude = waypoint.latitude
    msg.longitude = waypoint.longitude
    rospy.loginfo("Sending goal: " + str(waypoint.latitude) + "; " + str(waypoint.longitude))
    self.goal_pub.publish(msg)


def main():
  wps = SendWaypoints()
  # Waypoints List
  wp_l = []
  
  # Waypoint List (central alameda)
  # wp_1 = Waypoint(1, 38.7367705667847, -9.13759324059514)
  # wp_l.append(wp_1)
  
  # wp_2 = Waypoint(2, 38.736868377102226, -9.137488634441356)
  # wp_l.append(wp_2)

  # wp_3 = Waypoint(3, 38.73694840362603, -9.13761201605864)
  # wp_l.append(wp_3)

  # Waypoint List (central alameda)
  wp_1 = Waypoint(1, 38.54179115672379,-7.9628835591599305)
  wp_l.append(wp_1)
  
  wp_2 = Waypoint(2, 38.54179115672379,-7.962768894722129)
  wp_l.append(wp_2)

  wp_3 = Waypoint(3, 38.54170623371354,-7.9628835591599305)
  wp_l.append(wp_3)

#rostopic pub /jackal0/waypoint_coordinator/goal_request coordinates_waypoint_manager/WaypointRequest


  #Alternative Waypoint List (right-side alameda)
  # wp_1 = Waypoint(1, 38.7370090772706, -9.137950644953905)
  # wp_l.append(wp_1)
  
  # wp_2 = Waypoint(2, 38.7370242456737, -9.13772064552603)
  # wp_l.append(wp_2)

  # wp_3 = Waypoint(3, 38.737030522253335, -9.137618721581319)
  # wp_l.append(wp_3)

 
  for wp in wp_l:
      wps.execute(wp)

if __name__ == '__main__':
    main()
