// Generated by gencpp from file core_msgs/MapInfo.msg
// DO NOT EDIT!


#ifndef CORE_MSGS_MESSAGE_MAPINFO_H
#define CORE_MSGS_MESSAGE_MAPINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace core_msgs
{
template <class ContainerAllocator>
struct MapInfo_
{
  typedef MapInfo_<ContainerAllocator> Type;

  MapInfo_()
    : header()
    , size(0)
    , initialized(false)
    , volume(0.0)  {
    }
  MapInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , size(0)
    , initialized(false)
    , volume(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint64_t _size_type;
  _size_type size;

   typedef uint8_t _initialized_type;
  _initialized_type initialized;

   typedef float _volume_type;
  _volume_type volume;





  typedef boost::shared_ptr< ::core_msgs::MapInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::core_msgs::MapInfo_<ContainerAllocator> const> ConstPtr;

}; // struct MapInfo_

typedef ::core_msgs::MapInfo_<std::allocator<void> > MapInfo;

typedef boost::shared_ptr< ::core_msgs::MapInfo > MapInfoPtr;
typedef boost::shared_ptr< ::core_msgs::MapInfo const> MapInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::core_msgs::MapInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::core_msgs::MapInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::core_msgs::MapInfo_<ContainerAllocator1> & lhs, const ::core_msgs::MapInfo_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.size == rhs.size &&
    lhs.initialized == rhs.initialized &&
    lhs.volume == rhs.volume;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::core_msgs::MapInfo_<ContainerAllocator1> & lhs, const ::core_msgs::MapInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace core_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::core_msgs::MapInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::core_msgs::MapInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::core_msgs::MapInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::core_msgs::MapInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::core_msgs::MapInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::core_msgs::MapInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::core_msgs::MapInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7c3dc73401a0398b17fe75c574b69332";
  }

  static const char* value(const ::core_msgs::MapInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7c3dc73401a0398bULL;
  static const uint64_t static_value2 = 0x17fe75c574b69332ULL;
};

template<class ContainerAllocator>
struct DataType< ::core_msgs::MapInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "core_msgs/MapInfo";
  }

  static const char* value(const ::core_msgs::MapInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::core_msgs::MapInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Information associated to Map\n"
"# Header\n"
"Header header\n"
"\n"
"# Size of map\n"
"uint64 size\n"
"\n"
"# Mapper Initialised\n"
"bool initialized\n"
"\n"
"# Volume \n"
"float32 volume\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::core_msgs::MapInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::core_msgs::MapInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.size);
      stream.next(m.initialized);
      stream.next(m.volume);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MapInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::core_msgs::MapInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::core_msgs::MapInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "size: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.size);
    s << indent << "initialized: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.initialized);
    s << indent << "volume: ";
    Printer<float>::stream(s, indent + "  ", v.volume);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CORE_MSGS_MESSAGE_MAPINFO_H
