// Generated by gencpp from file coordinates_waypoint_manager/WaypointRequest.msg
// DO NOT EDIT!


#ifndef COORDINATES_WAYPOINT_MANAGER_MESSAGE_WAYPOINTREQUEST_H
#define COORDINATES_WAYPOINT_MANAGER_MESSAGE_WAYPOINTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace coordinates_waypoint_manager
{
template <class ContainerAllocator>
struct WaypointRequest_
{
  typedef WaypointRequest_<ContainerAllocator> Type;

  WaypointRequest_()
    : latitude(0.0)
    , longitude(0.0)
    , orientation(0.0)  {
    }
  WaypointRequest_(const ContainerAllocator& _alloc)
    : latitude(0.0)
    , longitude(0.0)
    , orientation(0.0)  {
  (void)_alloc;
    }



   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _orientation_type;
  _orientation_type orientation;





  typedef boost::shared_ptr< ::coordinates_waypoint_manager::WaypointRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coordinates_waypoint_manager::WaypointRequest_<ContainerAllocator> const> ConstPtr;

}; // struct WaypointRequest_

typedef ::coordinates_waypoint_manager::WaypointRequest_<std::allocator<void> > WaypointRequest;

typedef boost::shared_ptr< ::coordinates_waypoint_manager::WaypointRequest > WaypointRequestPtr;
typedef boost::shared_ptr< ::coordinates_waypoint_manager::WaypointRequest const> WaypointRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::coordinates_waypoint_manager::WaypointRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::coordinates_waypoint_manager::WaypointRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::coordinates_waypoint_manager::WaypointRequest_<ContainerAllocator1> & lhs, const ::coordinates_waypoint_manager::WaypointRequest_<ContainerAllocator2> & rhs)
{
  return lhs.latitude == rhs.latitude &&
    lhs.longitude == rhs.longitude &&
    lhs.orientation == rhs.orientation;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::coordinates_waypoint_manager::WaypointRequest_<ContainerAllocator1> & lhs, const ::coordinates_waypoint_manager::WaypointRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace coordinates_waypoint_manager

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::coordinates_waypoint_manager::WaypointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coordinates_waypoint_manager::WaypointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::coordinates_waypoint_manager::WaypointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::coordinates_waypoint_manager::WaypointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coordinates_waypoint_manager::WaypointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coordinates_waypoint_manager::WaypointRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::coordinates_waypoint_manager::WaypointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "530282eb8394bfbb078ecfae5999ac31";
  }

  static const char* value(const ::coordinates_waypoint_manager::WaypointRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x530282eb8394bfbbULL;
  static const uint64_t static_value2 = 0x078ecfae5999ac31ULL;
};

template<class ContainerAllocator>
struct DataType< ::coordinates_waypoint_manager::WaypointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "coordinates_waypoint_manager/WaypointRequest";
  }

  static const char* value(const ::coordinates_waypoint_manager::WaypointRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::coordinates_waypoint_manager::WaypointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 latitude\n"
"float64 longitude\n"
"float64 orientation\n"
;
  }

  static const char* value(const ::coordinates_waypoint_manager::WaypointRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::coordinates_waypoint_manager::WaypointRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.orientation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WaypointRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::coordinates_waypoint_manager::WaypointRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::coordinates_waypoint_manager::WaypointRequest_<ContainerAllocator>& v)
  {
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "orientation: ";
    Printer<double>::stream(s, indent + "  ", v.orientation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COORDINATES_WAYPOINT_MANAGER_MESSAGE_WAYPOINTREQUEST_H
